{
  "openapi": "3.0.0",
  "info": {
    "title": "API Musician",
    "version": "1.0.0"
  },
  "paths": {
    "/auth/login": {
      "post": {
        "responses": {
          "200": {
            "requestBody": {
              "content": {
                "application/json": {
                  "schema": { "$ref": "#/components/schemas/RequestLogin" }
                }
              }
            },
            "content": {
              "application/json": {
                "example": {
                  "token": "seu_token_de_autenticação"
                }
              }
            }
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "message": "credenciais inválidas"
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": { "$ref": "#/components/schemas/RequestLogin" }
            }
          }
        }
      }
    },
    "/auth/register": {
      "post": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "example": {
                  "message": "usuário criado com sucesso"
                }
              }
            }
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "message": "falha ao criar usuário"
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": { "$ref": "#/components/schemas/RequestRegister" }
            }
          }
        }
      }
    },
    "/create/album": {
      "post": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "example": {
                  "message": "álbum criado com sucesso"
                }
              }
            }
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "message": "falha ao criar álbum]"
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": { "$ref": "#/components/schemas/RequestAlbum" }
            }
          }
        }
      }
    },
    "/create/music/:id": {
      "post": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "example": {
                  "message": "música criada com sucesso"
                }
              }
            }
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "message": "falha ao criar música"
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "query",
            "description": "ID do álbum a qual a música pertence",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": { "$ref": "#/components/schemas/RequestMusic" }
            }
          }
        }
      }
    },
    "/get/music": {
      "get": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "example": [
                  {
                    "id": "",
                    "imageUrl": "",
                    "authorName": "",
                    "name": "",
                    "description": "",
                    "releaseDate": "",
                    "musicUrl": ""
                  }
                ]
              }
            }
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "message": "falha ao buscar músicas"
                }
              }
            }
          }
        }
      }
    },
    "/get/artist": {
      "get": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "example": [
                  {
                    "id": "",
                    "username": "",
                    "imageUrl": "",
                    "album": []
                  }
                ]
              }
            }
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "message": "falha ao buscar músicas"
                }
              }
            }
          }
        }
      }
    },
    "/get/album": {
      "get": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "example": [
                  {
                    "id": "",
                    "imageUrl": "",
                    "authorName": "",
                    "name": "",
                    "description": "",
                    "releaseDate": "",
                    "musics": []
                  }
                ]
              }
            }
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "message": "falha ao buscar músicas"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "RequestLogin": {
        "type": "object",
        "properties": {
          "username": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "required": ["username", "password"]
      },
      "RequestRegister": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "username": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "required": ["username", "password"]
      },
      "RequestAlbum": {
        "type": "object",
        "properties": {
          "image": {
            "type": "string",
            "format": "binary"
          },
          "name": {
            "type": "string"
          },
          "authorName": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "releaseDate": {
            "type": "string",
            "format": "iso"
          }
        },
        "required": ["music", "image", "name", "authorName", "description", "releaseDate"]
      },
      "RequestMusic": {
        "type": "object",
        "properties": {
          "music": {
            "type": "string",
            "format": "binary"
          },
          "image": {
            "type": "string",
            "format": "binary"
          },
          "name": {
            "type": "string"
          },
          "authorName": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "releaseDate": {
            "type": "string",
            "format": "iso"
          }
        },
        "required": ["music", "image", "name", "authorName", "description", "releaseDate"]
      }
    }
  }
}
